# -*- coding: utf-8 -*-
"""Data Assessing and Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZMaVLD90-Tm0hL-W-coqSnJMbhsaL2I
"""

import pandas as pd
import numpy as np
import re

"""**loading data** including file


"""

patients=pd.read_csv('patients.csv')
tratments=pd.read_csv('treatments.csv')
adverse_reactions=pd.read_csv('adverse_reactions.csv')
treatments_cut=pd.read_csv('treatments_cut.csv')

"""seeing the data"""



patients.head()

tratments.head()

treatments_cut.head()

adverse_reactions.head()

"""### 1. Write a summary for your data

This is a dataset about 500 patients of which 350 patients participated in a clinical trial. None of the patients were using Novodra (a popular injectable insulin) or Auralin (the oral insulin being researched) as their primary source of insulin before. All were experiencing elevated HbA1c levels.

All 350 patients were treated with Novodra to establish a baseline HbA1c level and insulin dose. After 4 weeks, which isn’t enough time to capture all the change in HbA1c that can be attributed by the switch to Auralin or Novodra:

- 175 patients switched to Auralin for 24 weeks
- 175 patients continued using Novodra for 24 weeks

Data about patients feeling some adverse effects is also recorded.

### 2. Write Column descriptions

#### **Table** -> `patients`:

- `patient_id`: the unique identifier for each patient in the Master Patient Index (i.e. patient database) of the pharmaceutical company that is producing Auralin
- `assigned_sex`: the assigned sex of each patient at birth (male or female)
- `given_name`: the given name (i.e. first name) of each patient
- `surname`: the surname (i.e. last name) of each patient
- `address`: the main address for each patient
- `city`: the corresponding city for the main address of each patient
- `state`: the corresponding state for the main address of each patient
- `zip_code`: the corresponding zip code for the main address of each patient
- `country`: the corresponding country for the main address of each patient (all United states for this clinical trial)
- `contact`: phone number and email information for each patient
- `birthdate`: the date of birth of each patient (month/day/year). The inclusion criteria for this clinical trial is age >= 18 (there is no maximum age because diabetes is a growing problem among the elderly population)
- `weight`: the weight of each patient in pounds (lbs)
- `height`: the height of each patient in inches (in)
- `bmi`: the Body Mass Index (BMI) of each patient. BMI is a simple calculation using a person's height and weight. The formula is BMI = kg/m2 where kg is a person's weight in kilograms and m2 is their height in metres squared. A BMI of 25.0 or more is overweight, while the healthy range is 18.5 to 24.9. The inclusion criteria for this clinical trial is 16 >= BMI >= 38.

#### **Table** -> `treatments` and `treatment_cut`:

- `given_name`: the given name of each patient in the Master Patient Index that took part in the clinical trial
- `surname`: the surname of each patient in the Master Patient Index that took part in the clinical trial
- `auralin`: the baseline median daily dose of insulin from the week prior to switching to Auralin (the number before the dash) and the ending median daily dose of insulin at the end of the 24 weeks of treatment measured over the 24th week of treatment (the number after the dash). Both are measured in units (shortform 'u'), which is the international unit of measurement and the standard measurement for insulin.
- `novodra`: same as above, except for patients that continued treatment with Novodra
- `hba1c_start`: the patient's HbA1c level at the beginning of the first week of treatment. HbA1c stands for Hemoglobin A1c. The HbA1c test measures what the average blood sugar has been over the past three months. It is thus a powerful way to get an overall sense of how well diabetes has been controlled. Everyone with diabetes should have this test 2 to 4 times per year. Measured in %.
- `hba1c_end`: the patient's HbA1c level at the end of the last week of treatment
- `hba1c_change`: the change in the patient's HbA1c level from the start of treatment to the end, i.e., hba1c_start - hba1c_end. For Auralin to be deemed effective, it must be "noninferior" to Novodra, the current standard for insulin. This "noninferiority" is statistically defined as the upper bound of the 95% confidence interval being less than 0.4% for the difference between the mean HbA1c changes for Novodra and Auralin (i.e. Novodra minus Auralin).

#### **Table** -> `adverse_reactions`

- `given_name`: the given name of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)
- `surname`: the surname of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)
- `adverse_reaction`: the adverse reaction reported by the patient

### 3. Add any additional information

Additional useful information:

- Insulin resistance varies person to person, which is why both starting median daily dose and ending median daily dose are required, i.e., to calculate change in dose.
- It is important to test drugs and medical products in the people they are meant to help. People of different age, race, sex, and ethnic group must be included in clinical trials. This diversity is reflected in the patients table.

### Types of Assessment
There are 2 types of assessment styles

- `Manual` - Looking through the data manually in google sheets
- `Programmatic` - By using pandas functions such as info(), describe() or sample()

### Steps in Assessment
There are 2 steps involved in Assessment

- Discover
- Document

**Manual Assessment**-> by seeing data using eye and trying to find mistake in data s called manual Assessment

**Automatic Assessment**-> in Automatic Assessment we use pandas function or write code to find error n data
pandas function used are :-
1.head and tail
2.sample
3.isnull
4.duplicated
5.describe
"""

patients.head()

patients.tail()

"""**We use sample function to check wherther the data in middle is have any error we run this function many tiimes to find error **"""

patients.sample()

patients.info()

"""we use is null function to check which data is not in table"""

patients[patients['address'].isnull()]

patients[patients['city'].isnull()]

"""**checking datatype for memory management**"""

tratments.info()

treatments_cut.info()

adverse_reactions.info()

"""**Finding duplicates**"""

patients.duplicated().sum()

patients['patient_id'].duplicated().sum()

patients[patients.duplicated(subset=['given_name','surname'])]

"""this are those who are duplecated because there all entries are same

to finding duplicates follow these steps:
1.first check their id
2.check thier name and surname
3.their contact detail
"""

tratments.duplicated().sum()

"""in this column one duplecated is find so we check who is that"""

tratments[tratments.duplicated()]

adverse_reactions.duplicated().sum()

patients.describe()

tratments.describe()

tratments.sort_values('hba1c_start')

"""# **Important note**:-Assessing data is an iterative process

we Assessing again and agian after cleaning because we know that **first time finding all mistake is not possible**

### Data Quality Dimensions

- Completeness -> is data missing?
- Validity -> is data invalid -> negative height -> duplicate patient id
- Accuracy -> data is valid but not accurate -> weight -> 1kg
- Consistency -> both valid and accurate but written differently -> New Youk and NY

### Order of severity

Completeness <- Validity <- Accuracy <- Consistency

### Data Cleaning Order

1. Quality -> Completeness
2. Tidiness
3. Quality -> Validity
4. Quality -> Accuracy
5. Quality -> Consistency

#### Steps involved in Data cleaning
- Define
- Code
- Test

`Always make sure to create a copy of your pandas dataframe before you start the cleaning process`

**Cleaning Data**
"""

patients_df=patients.copy()
tratments_df=tratments.copy()
tratments_cut_df=treatments_cut.copy()
adverse_reactions_df=adverse_reactions.copy()

"""### **Defining problem** in patients
**completeness problem**->Replace all missing values of patients_df with **"NO data found so collect when they comes"**

"""

#Code
patients_df.fillna("NO data found so collect when they comes",inplace=True)

#test
patients_df.info()

tratments_df.head()

"""### **Defining problem** in tratments
sub hba1c_start from hba1c_end to get change in values

"""

# solution/code
tratments_df['hba1c_change']=tratments_df['hba1c_start']-tratments_df['hba1c_end']
tratments_cut_df['hba1c_change']=tratments_cut_df['hba1c_start']-tratments_cut_df['hba1c_end']

tratments_df.info()

tratments_cut_df.info()

"""all completion issue has done now
###**tideness issue**

**in patients table we use regex for seprating phone no and email**
"""



patients_df['phone'] = patients_df["contact"].apply(lambda x: find_contact_details(x)).apply(lambda x:x[0])
patients_df['email'] = patients_df["contact"].apply(lambda x: find_contact_details(x)).apply(lambda x:x[1])

patients_df.head()

patients_df.drop(columns='contact',inplace=True)

"""### **merging two table treatments_df and treatments_cut_df**"""

treatments_df = pd.concat([tratments_df,tratments_cut_df])

treatments_df

treatments_df = treatments_df.melt(id_vars=['given_name', 'surname' ,'hba1c_start', 'hba1c_end','hba1c_change'],var_name='type',value_name='dosage_range')

treatments_df

"""removing extra row"""

treatments_df = treatments_df[treatments_df['dosage_range'] != '-']

treatments_df

treatments_df['dosage_start'] = treatments_df['dosage_range'].str.split('-').str.get(0)
treatments_df['dosage_end'] = treatments_df['dosage_range'].str.split('-').str.get(1)

treatments_df

treatments_df.drop(columns='dosage_range',inplace=True)

treatments_df['dosage_start'] = treatments_df['dosage_start'].str.replace('u','')
treatments_df['dosage_end'] = treatments_df['dosage_end'].str.replace('u','')

treatments_df['dosage_start'] = treatments_df['dosage_start'].astype('int')
treatments_df['dosage_end'] = treatments_df['dosage_end'].astype('int')

treatments_df

treatments_df = treatments_df.merge(adverse_reactions_df, how ='left', on=['given_name','surname'])

treatments_df