# -*- coding: utf-8 -*-
"""Data Gathering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192tVFdMAWKIS5nIgQ7G1G4tSFDUdin20

## **Reading csv file**

**Importing pandas**
"""

import pandas as pd

"""**Fetching data(CSV file) from your own computer or machine**"""

df=pd.read_csv('batter.csv')
df

"""**Opening a csv file from a url**"""

import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

"""**Sep Parameter**->is **used** when you are **dealing **with** non commas seprated file** such as you deals with **tap seprated file(TSV)**

**names**=is **used** when you **dont have colume** name ** for giving colume name we use names **
"""

pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['sno','name','release_year','rating','votes','genres'])

"""**Index_col Parameter**-> used when you have two column or you want to make your one column as index"""

pd.read_csv('aug_train.csv',index_col='enrollee_id')

"""**Header parameter** -> it s used when your header is column or **you want to make column as header **"""

pd.read_csv('test.csv',header=1)

"""**use_cols parameter**-> it is used you have alot of column or  **you  know on which row you wnat to work**"""

filter_col=pd.read_csv('aug_train.csv',usecols=['enrollee_id','gender','education_level'])
print(filter_col)

"""**Squeeze parameter** is used when you are deleing with series not dataframe
this make a dataframe to a series
"""

data = pd.read_csv('aug_train.csv', usecols=['gender'])
data = data['gender']
print(data)

"""**Skiprows/ Parameter**-> it s used to skip te that oarticular row which you mention"""

data=pd.read_csv('aug_train.csv')
data

data=pd.read_csv('aug_train.csv',skiprows=[1,5])
data

"""**nrows Parameter**-> it gives you only that much row which you specify"""

data=pd.read_csv('aug_train.csv',nrows=100)
data

"""**dtype parameter**-> this is used to change the data type"""

data=pd.read_csv('aug_train.csv')
data.info()

data=pd.read_csv('aug_train.csv',dtype={'target':int})
data.info()

"""**Handling dates**"""

data=pd.read_csv('IPL Matches 2008-2020.csv').info()
data

data=pd.read_csv('IPL Matches 2008-2020.csv',parse_dates=['date']).info()
data

"""**Loading a huge dataset in chunks**"""

dfs=pd.read_csv('aug_train.csv',chunksize=5000)

for chunks in dfs:
    print(chunks.shape)